### ISSUE TITLE
Lack of 100% code coverage

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5-ui-default#100] opened 2016-10-20 09:46 UTC
`list/listitem.js` doesn't have 100% CC:

![image](https://cloud.githubusercontent.com/assets/2270764/19554854/bb825650-96ba-11e6-8f9f-9b832c583e08.png)

![image](https://cloud.githubusercontent.com/assets/2270764/19554803/8538e8f2-96ba-11e6-9861-40ed2c41b12f.png)

**Comment by oleq** [comment] 2016-10-24 12:45
Duplicate of https://github.com/ckeditor/ckeditor5-ui-default/issues/97.

**Closed as completed by oleq** 2016-10-24 12:45 UTC
Labels: resolution:duplicate
