### ISSUE TITLE
Stop listening scroll event when it is not necessary - sticky toolbar

### ISSUE THREAD

**Issue by oskarwrobel** [ckeditor/ckeditor5-ui-default#80] opened 2016-09-20 13:24 UTC
FollowUp of https://github.com/ckeditor/ckeditor5-ui-default/issues/74
See: https://github.com/ckeditor/ckeditor5-ui-default/pull/75#discussion_r79584396

**Comment by oleq** [comment] 2017-01-03 14:40
More or less a duplicate of https://github.com/ckeditor/ckeditor5-ui-default/issues/14.

**Closed as completed by oleq** 2017-01-03 14:40 UTC
Labels: status:confirmed, resolution:duplicate, type:enhancement
